### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by LionsAd** [BitPhinix/slate-yjs#1]
Just a little nitpick - it is Yjs not YJs.

I think - and I never asked Kevin _ that the Y is a fork showing the merge, the js then is just a subscript for the implemented language.

This issue can be closed, really just wanted to say that this is great work!

**Comment by BitPhinix** [comment]
Thanks for pointing that out @LionsAd! I will fix the spelling asap since it's not only in the readme and a breaking change in the future if people are using it.
