### ISSUE TITLE
Question : Using Firebase Realtime DB as backend 

### ISSUE THREAD

**Issue by cngeru** [BitPhinix/slate-yjs#131]
Is it possible to use the firebase realtime database as the backend ?

**Comment by BitPhinix** [comment]
Hi @cngeru,

Since slate-yjs is completely completely independent from the server side implementation it in fact can be used with any Backend YJs can be used with. I haven't yet tried using a firebase realtime db but it seems to be possible: https://github.com/yjs/yjs/issues/189
