### ISSUE TITLE
Use React 16 instead of 17

### ISSUE THREAD

**Issue by tmathew0309** [BitPhinix/slate-yjs#175]
Is it possible to declare a peerDependency on React 16 instead of 17? Don't think you actually use anything 17 specific in this repo and we haven't upgraded to React 17 yet but want to be able to use this.

**Comment by tmathew0309** [comment]
Hi @BitPhinix can we release a version with this fix? Looks like the latest 2.2.0 version doesn't have this. Thanks!

**Comment by BitPhinix** [comment]
Done 👍
