### ISSUE TITLE
`delta.insert.join` is broken

### ISSUE THREAD

**Issue by dmonad** [BitPhinix/slate-yjs#188]
Hi, 

I just realized that I broke your editor binding in my latest Yjs release. 

`Y.Text` operates on [Quill Deltas](https://quilljs.com/docs/delta/). `event.delta` is a well-formatted Quill Delta. I realized that `event.changes.delta` is an Array Delta (an adaptation of the Quill Delta that operates on Arrays instead of Strings). 

I fixed this issue and made `event.changes.delta` a proper Quill delta. So you no longer need to do `delta.insert.join()`. Since `delta.insert` is a string now, you will actually get an error message as a user in https://gitter.im/Yjs/community reported. 

You can fix this in a backward-compatible way by listening to `event.delta` which is (and has always been) a Quill delta. So new and old versions of Yjs will work.

**Comment by BitPhinix** [comment]
Hi @dmonad,

Thank you so much for reporting and investigating this issue. I'm currently on a work trip and have been working on some code cleanup which will resolve this anyway.

Will push the fix on the weekend.

**Comment by BitPhinix** [comment]
Will be fixed with https://github.com/BitPhinix/slate-yjs/issues/188
