### ISSUE TITLE
I can't seem to start a collaborative session in offline mode and go online after the fact.

### ISSUE THREAD

**Issue by aliak00** [BitPhinix/slate-yjs#192]
Hi, I'm trying to use slate-yjs to see how things can work, and I'm using y-websocket to test things out. I'm having trouble with the initial setup of the editor+slate-yjs. The problem seems to be that `withYjs` requires a `sharedType` and while `shareType` is ok with  a `[]` initial value, the slate editor is not (i.e. an empty document is actually a single block with an empty text node).

So these are the steps I take

1. Get the current value of my document (from storage) - if it's a new document and doesn't exist, set the value to the `emptyDocument`
2. Initialize a `sharedType` with `Y.Doc.getArray`
3. Initialize a provider with `new WebsocketProvider` which requires the `doc` and also sets the "slug" for the doc
4. Create the editor with `withYjs` which requires the `sharedType`

Then I have a `useEffect` that is dependent on `provider` that sets the events on the `provider` (sync and status) and:

5. Calls `toSharedType` with the current value of the document.

The problem is at the very start. User A stars a document with slug `X` and User B starts a document with slug `X`. If this document does not exist in storage it will be given the empty slate doc, which is:

```
{
  type: 'paragraph',
  children: [{text: ''}],
}
```

And this will be what is called with `toSharedType`

And when User B comes in, they also get the empty document. Now when they both go online, the `sharedType` is updated with two empty documents and becomes this:

```
[{
  type: 'paragraph',
  children: [{text: ''}],
},
{
  type: 'paragraph',
  children: [{text: ''}],
}]
```

If I do not call `toSharedType` on an initial empty document, then the slate editor does not work and i get

```
react-editor.ts:458 Uncaught Error: Cannot resolve a Slate point from DOM point: [object HTMLDivElement],0
    at Object.toSlatePoint (react-editor.ts:458)
    at Object.toSlateRange (react-editor.ts:516)
    at HTMLDocument.<anonymous> (editable.tsx:422)
    at invokeFunc (debounce.js:95)
    at leadingEdge (debounce.js:105)
    at HTMLDocument.debounced (debounce.js:172)
```

Any help here would be awesome!

**Comment by BitPhinix** [comment]
Hi Ali,

you can solve this 2 ways, either by initializing the document server-side with a custom y-websocket server like here: https://github.com/BitPhinix/slate-yjs-example/blob/306364182f24414503c08d0fdbb412f649417696/server/server.ts (the code is using an old version of slate-yjs but it should be almost identical)

Or, in a very hacky way client-side like in the example project here: https://github.com/BitPhinix/slate-yjs-example/blob/d8be483453e9f5968c6ed0013f56478048e2e3aa/src/Client.tsx#L79

Hope this helps!

**Comment by BitPhinix** [comment]
Sorry, didn't read the offline part in the title. Not sure about that one tbh, you should ask about providing an initial value for offline clients in https://discuss.yjs.dev/ (Kevin, the creator of yjs is super active there and hopefully can answer your question)

**Comment by aliak00** [comment]
Ah ok. Thanks! Will probably ask there then 🙇

**Comment by aliak00** [comment]
For reference: https://discuss.yjs.dev/t/initial-offline-value-of-a-shared-document/465
