### ISSUE TITLE
Prevent y-websocket initial value from entering slate-history undos

### ISSUE THREAD

**Issue by SamDuvall** [BitPhinix/slate-yjs#205]
I'm running into an issue where loading the initial value from `y-websocket` is adding an operation into undos from `slate-history` that I don't want. Having that initial value operation in `editor.history` allows the user to click undo and wipe out the document, which is not desirable.

I'm creating my editor like `slate-yjs-example`
```
  const yDoc = new Y.Doc()
  const sharedType = yDoc.getArray<SyncElement>('content')
  const editor = withYjs(withHistory(withReact(createEditor())), sharedType)
```

I added a hack to pop off the initial value operation from the history for now:
```
  const onLoad = () => {
    editor.history.undos.pop()
    sharedType.unobserveDeep(onLoad)
  }
  sharedType.observeDeep(onLoad)
```

I'm not sure if a fix belongs in `slate-yjs` or somewhere else, but does anyone have a better approach to using `slate-yjs` in combinations with `y-websocket` & `slate-history` for the initial value?

**Comment by BitPhinix** [comment]
Hi @SamDuvall,

Another way you could solve this is by wrapping `editor.applyOperation` with a handler that checks if `YjsEditor.isRemote(editor)` is true and then wrapping the next call with `HistoryEditor.withoutSaving`

I haven't actually tested it, but it should work 😄

**Comment by SamDuvall** [comment]
@BitPhinix, thank you. That was an excellent suggestion and worked beautifully.

I can't think of a good reason why one would want remote changes to creep into their local history. I wish there was an easy way to add this to `slate-jys`, but it feels wrong to require `slate-history` in `slate-yjs` even though I bet a large majority of people using `slate-yjs` use `slate-history` as well. Below is the code I added after creating the editor for anyone else who is interested:

```
  const { apply } = editor
  editor.apply = (...args) => {
    if (YjsEditor.isRemote(editor)) {
      HistoryEditor.withoutSaving(editor, () => {
        apply.apply(editor, args)
      })
    } else {
      apply.apply(editor, args)
    }
  }
```

**Comment by BitPhinix** [comment]
Awesome, glad I could help!

I haven't yet added this to `slate-yjs` because I'm planning to add another history handling plugin based on `Y.UndoManager` to have proper Yjs history support. I'm really busy at the moment but will get back to it in the coming months
