### ISSUE TITLE
Slate editor initial sync error

### ISSUE THREAD

**Issue by kashyaparjun** [BitPhinix/slate-yjs#210]
Hi,

I have a slate-yjs editor which gets fed content from the server side. At the server side, I insert the content to document like this `doc.getArray('content').insert(0, JSON.parse(content));`. On the front end, the yjs part is syncing the content, I can also see it in the sharedType array, but the slate editor value doesn't change. I cannot call toSharedType on the frontend as this would duplicate the content. 

Please help.

Thanks and regards,
Arjun Kashyap

**Comment by BitPhinix** [comment]
Hi @kashyaparjun,

Inserting the content like this won't work because `slate-yjs` expects the slate doc to be represented as/converted into nested Yjs types. You can use the exposed `toSharedType` helper to do so

Hope this helps, let me know if you need help with anything else 😄

**Comment by kashyaparjun** [comment]
Do I have to use `toSharedType` even when I'm loading the content on the server side? I did try using it in the 'sync' callback and it duplicated the content already present. It'd be great if you can share any implementation that you have of this.

**Comment by kashyaparjun** [comment]
The issue was solved by adding slate-yjs to the server and using the `toSharedType` function to add content to the yjs doc.

Thank you @BitPhinix
