### ISSUE TITLE
[Question] Pressing backspace moves the cursor of another user

### ISSUE THREAD

**Issue by devgeni** [BitPhinix/slate-yjs#226]
I integrated slate-yjs with [@udecode/slate-plugins](https://github.com/udecode/slate-plugins) and the problem I've encountered is that when one user presses backspace or replaces some selected text the cursor of another user is moved to the position of the first user's cursor. What could be the problem?

**Comment by devgeni** [comment]
Here is the short video of this issue:

https://devgeni.github.io/slate-yjs-udecode.mp4

**Comment by skokenes** [comment]
@devgeni see the fix linked in the PR above
