### ISSUE TITLE
Update y-protocols to 1.0.5

### ISSUE THREAD

**Issue by nemanja-tosic** [BitPhinix/slate-yjs#233]
y-protocols has added the conditional exports pattern in 1.0.5. We need this as we use slate-yjs on both node and on the frontend.

**Comment by BitPhinix** [comment]
Hi @nemanja-tosic,

Thanks for this issue, just create a pr for it and I'll merge it with the next release 👍 . I can do it as well but will probably take until the weekend

**Comment by BitPhinix** [comment]
Released with version 2.1.0
