### ISSUE TITLE
Assumes causal ordering of Yjs events?

### ISSUE THREAD

**Issue by beorn** [BitPhinix/slate-yjs#25]
Hi,

I'm trying to wrap my head around sync-ing CRDTs and the integration with non-CRDT data models like Slate.  If I understand correctly, it seems that you translate between Slate ops and Yjs events ([yjsEditor.ts](https://github.com/BitPhinix/slate-yjs/blob/master/src/plugin/yjsEditor.ts)).

But wouldn't this cause a problem since CRDT events/ops are not regular ordered deltas, but operations that can be applied "out of order" with complicated conflict resolution based on logical clocks and LWW registers etc?  For example, a property update might come in that when applied should not result in any change because there's a newer value of that property already applied.

I.e., wouldn't the only authoritative snapshot state be the one you have to ask Yjs for, not one you can compute yourself based on applying Yjs events (as you'd have to implement all the CRDT conflict resolution machinery)?

Apologies if I am misunderstanding something.

**Comment by BitPhinix** [comment]
Hi @beorn,

You are correct, slate-yjs just translates the events. It would cause an issue if the (local) yjs state would change while applying operations. The thing that saves us, in this case, is the fact that js is a single threaded language so you don't end up in a state where the yjs doc is changed while you type something which would cause the need to apply events. If the yjs doc changes after you type yjs deal with applying the changes you made while the other person typed. I hope that clears things up, feel free to ask if anything is unclear.

**Comment by beorn** [comment]
Ok, but what about the case where the changes from two different sources are delivered to your local editor out-of-order?  I.e., the logical time order is different from the delivery time order.

**Comment by BitPhinix** [comment]
If multiple changes are delivered from multiple sources yjs will transform them to the equivalent in the current state. Since the slate doc and the yjs doc always reflect the same state, the "transformed" yjs events will always be the equivalent to the action performed by the other user in the current document state (even if they arrive out of order).
