### ISSUE TITLE
Awareness is copied on independent instances inside one document

### ISSUE THREAD

**Issue by creativefctr** [BitPhinix/slate-yjs#286]
Hi,
I am using the awareness option with a Y.js document that has multiple sub documents for multiple Slate instances.
Awareness is registered on all instances. As you can see, the cursor from one sub doc of the main doc object is also applied on other instances, which is wrong!

![image](https://user-images.githubusercontent.com/9378281/125457236-2df397c2-7187-4b96-9334-539662e8d82a.png)

the document structure is like:

```
{
       slate1: [],
       slate2: [],
       ...
}
```

**Comment by BitPhinix** [comment]
Hi @creativefctr,

the cursors are synced using awareness (which is bound to the document and not the shared type) so this is to be expected for now.

Since a single user can (under normal circumstances) have only a single selection at a time you could as a workaround store some sort of identifier (like the shared type key) on editor focus in the awareness local state and use that to figure out which editor the user has currently selected.

**Comment by creativefctr** [comment]
@BitPhinix Technically speaking, the shared type is a unique node in the document, so per-document awareness should also correctly detect the absolute path of that specific shared type object relative to the whole document. 
Anyway, I was thinking about using JavaScript's Proxy Object as a workaround to decorate the awareness object so that the changes are only routed to the currently focused editor (which can be detected by your solution).

**Comment by BitPhinix** [comment]
Next allows the customization of the cursor state storage key to solve this issue.

**Comment by rcbevans** [comment]
> Next allows the customization of the cursor state storage key to solve this issue.

Is this available yet?  I'm hitting the same issue right now with the page crashing with the following error:

```
Uncaught Error: yText isn't a descendant of root element
    getSlatePath location.ts:118
    absolutePositionToSlatePoint position.ts:43
    relativePositionToSlatePoint position.ts:78
    relativeRangeToSlateRange position.ts:272
    getRange useRemoteCursorOverlayPositions.tsx:64
    node_modules bundle.js:202241
    node_modules bundle.js:202236
    React 3
    useRemoteCursorOverlayPositions
```

If the ability to customize the cursor state storage key is not yet available, can you suggest a workaround?

**Comment by BitPhinix** [comment]
It is available, you can adjust it using the `cursorStateField` (and `cursorDataField`) option in `withCursors`

**Comment by rcbevans** [comment]
Just edited my comment, I found that myself looking at the exported d.ts, but didn't see it in any documentation.  Glad I found this issue :)
