### ISSUE TITLE
Update slate to 0.65.3

### ISSUE THREAD

**Issue by 108EAA0A** [BitPhinix/slate-yjs#292]
slate has fixed [IME bug](https://github.com/ianstormtaylor/slate/pull/4157) in 0.65.3. We need this as we use slate-yjs.

**Comment by dylans** [comment]
As a note, 0.66.0 should get released this week which has additional IME (and many other) fixes, https://github.com/ianstormtaylor/slate/pull/4436

**Comment by BitPhinix** [comment]
I'll just update it to latest 👍 Btw - the current version should work with the latest slate version as well. But you probably will run into typing issues. Haven't tested this yet but I can't image why it should't

**Comment by nemanja-tosic** [comment]
We use slate-yjs with 0.65.3 without issues.

**Comment by BitPhinix** [comment]
Supported in the next branch beta release.
