### ISSUE TITLE
Cursor decorator performance

### ISSUE THREAD

**Issue by BitPhinix** [BitPhinix/slate-yjs#294]
### Discussed in https://github.com/BitPhinix/slate-yjs/discussions/293

<div type='discussions-op-text'>

<sup>Originally posted by **bjarkih** August 18, 2021</sup>
Hi all, and thanks for great work on Slate Yjs!

I have a question around the performance of the cursor decorator provided by the sample `useCursors` implementation. When editing a document that another user is editing at the same time, we're updating the `decorate` function as the remote cursor positions change, which leads to frequent re-renderings of the Slate editor. For me, this leads to a visibly sluggish editor experience as soon as multiple users are editing the same part of the document tree.

Has anyone else encountered the same problem and, hopefully, found some solutions or workarounds? Any input appreciated!

Bjarki</div>

**Comment by nemanja-tosic** [comment]
Left a comment in the discussion with our approach: https://github.com/BitPhinix/slate-yjs/discussions/293#discussioncomment-1285673.

**Comment by BitPhinix** [comment]
Next has a new approach for a cursor plugin solving this issue
