### ISSUE TITLE
Yjs based history plugin

### ISSUE THREAD

**Issue by BitPhinix** [BitPhinix/slate-yjs#295]
slate-yjs should have a yjs backed history plugin to allow filtering the undo stack based on change origin without potentially causing editor crashes

**Comment by nemanja-tosic** [comment]
This would be awesome. We're looking into integrating with yjs undo right now as part of our collaboration plugin (slate-yjs with a custom socketio provider). Happy to help if you tell me what you had in mind!

**Comment by BitPhinix** [comment]
I haven't yet tried prototyping a concrete solution, so I'm not sure if this is going to work in the end. The idea is to write a custom implementation based on the https://github.com/yjs/yjs/blob/main/src/utils/UndoManager.js which also supports putting selections on the undo/redo stack. We can store selections on the stack using the relative position API and the changes just like the undomanager does. The implementation could be very similar to the slate history implementation itself, we could even use it under the hood to support plugins that where written based on it. In the end the goal is to have an API compatible drop-in replacement

**Comment by Fibs7000** [comment]
having the same problem I managed to connect slate-yjs to slate history with just one line added... (its a patch but it works)

In the yjsEditor.js file in the withYjs Method, just replace

```
sharedType.observeDeep((events) => {
        if (!YjsEditor.isLocal(e)) {
            YjsEditor.applyYjsEvents(e, events);
        }
    });

```

with this 
```
sharedType.observeDeep((events) => {
        if (!YjsEditor.isLocal(e)) {
          HistoryEditor.withoutSaving(editor, () => {
            YjsEditor.applyYjsEvents(e, events);
          })
        }
    });
```

and add this line on top
```
import {HistoryEditor} from "slate-history"
```

this just does not add the remote updates into the history

**Comment by BitPhinix** [comment]
Supported in the next brach beta release.

**Comment by bjarkih** [comment]
Thanks @BitPhinix 👏🏻 Are there any pre-built versions of the beta release, or just build from source for now?
