### ISSUE TITLE
Use  slate-yjs with Plate (slate-plugins)

### ISSUE THREAD

**Issue by vatz1905** [BitPhinix/slate-yjs#301]
Is there a way to use  slate-yjs with Plate ? or we must have a "plate-yjs" binding?

**Comment by BitPhinix** [comment]
I personally haven't used plate yet but I'm certain it is possible. https://github.com/BitPhinix/slate-yjs/discussions/291 might be helpful.

**Comment by vatz1905** [comment]
Thank you

בתאריך יום ו׳, 24 בספט׳ 2021 ב-18:59 מאת Eric Meier <
***@***.***>:
