### ISSUE TITLE
Please export slateYjsSymbol this is required for Y.UndoManager

### ISSUE THREAD

**Issue by Hideman85** [BitPhinix/slate-yjs#303]
As title said, Please export slateYjsSymbol this is required for Y.UndoManager as trackedOrigins to record the user action

**Comment by nemanja-tosic** [comment]
I'll do a PR for this today.

**Comment by BitPhinix** [comment]
V4 will allow you to define custom origins (a draft implementation is already present on the next branch). Will close this for now in favor of https://github.com/BitPhinix/slate-yjs/issues/304
