### ISSUE TITLE
Allow custom origins?

### ISSUE THREAD

**Issue by skokenes** [BitPhinix/slate-yjs#304]
Does this plugin support using custom origins when applying slate ops?

It looks like the underlying function supports it: https://github.com/BitPhinix/slate-yjs/blob/master/src/applyToYjs/index.ts#L39

However, in the plugin it looks like the origin is hardcoded to the slateYjsSymbol https://github.com/BitPhinix/slate-yjs/blob/master/src/plugin/yjsEditor.ts#L77-L81

Is there a way to override this on an editor by editor basis?

**Comment by nemanja-tosic** [comment]
It was not implemented as part of the initial work. What's there was only to support differentiating between yjs ops that came from the outside and those coming from the editor. I'm happy to do another PR if you give me a bit more info about the use case though.

**Comment by skokenes** [comment]
The use case we have is that we have servers that keep track of which yjs document updates came from which users via origins. If all clients have the same origin, we can't track this information.

**Comment by BitPhinix** [comment]
Supported in the next brach beta release.
