### ISSUE TITLE
NPM error: Could not resolve peer dependency slate.

### ISSUE THREAD

**Issue by RBSUS** [BitPhinix/slate-yjs#305]
I'm need to install slate-yjs but keep getting this error

![image](https://user-images.githubusercontent.com/68548194/137180755-8c3c2676-f3f1-4ff1-9f8d-70ee309e6f5c.png)

Any help would be greatly appreciated.

**Comment by ibaggu** [comment]
> I'm need to install slate-yjs but keep getting this error
> 
> ![image](https://user-images.githubusercontent.com/68548194/137180755-8c3c2676-f3f1-4ff1-9f8d-70ee309e6f5c.png)
> 
> Any help would be greatly appreciated.

Same here

**Comment by RBSUS** [comment]
try adding --force after your npm install slate-yjs

**Comment by ibaggu** [comment]
> try adding --force after your npm install slate-yjs

Thanks @RBSUS , this helped
