### ISSUE TITLE
Problem when pressing enter

### ISSUE THREAD

**Issue by creativefctr** [BitPhinix/slate-yjs#311]
Hi,
This section was already working fine, but recently, when I press enter to split text or create a new paragraph, I get this error:

Uncaught (in promise) Error: Unexpected content type in insert operation

![image](https://user-images.githubusercontent.com/9378281/142861734-0efb81a2-6646-43d9-8858-db03d140b3da.png)

After the error, Slate freezes and you can no longer type or edit anything.

slate-yjs version: 3.1.1
slate version: 0.63.0
yjs: 13.5.22

Any idea what might be causing this?

**Comment by BitPhinix** [comment]
You probably have multiple instances/versions of yjs loaded. Try `yarn why yjs` or `yarn dedupe` or add a workspace level resolution to force a specific version.

**Comment by creativefctr** [comment]
@BitPhinix Thanks. Yes, that was the issue.
