### ISSUE TITLE
incorrect selection after redo

### ISSUE THREAD

**Issue by ilya2204** [BitPhinix/slate-yjs#326]
https://user-images.githubusercontent.com/52297646/158056425-bfbdfe39-9faf-4287-8a0c-9bf4f8b75912.mp4

**Comment by BitPhinix** [comment]
This seems to be caused by https://github.com/BitPhinix/slate-yjs/issues/326, waiting on a reply to https://github.com/BitPhinix/slate-yjs/issues/326 in order to fix it
