### ISSUE TITLE
Can't compile against Yjs 13.5.28+

### ISSUE THREAD

**Issue by productivityindustries** [BitPhinix/slate-yjs#328]
Hello, I'm including in my project both slate-yjs and yjs as dependencies:
```
  "dependencies": {
      ...
      "slate-yjs": "^3.2.0",
      "yjs": "13.5.27",
      ...
```

everything worked smoothly until I bumped the yjs version, then I started getting typescript compilation errors:
```
Error: node_modules/slate-yjs/dist/main/applyToSlate/index.d.ts:8:66 - error TS2314: Generic type 'YEvent<T>' requires 1 type argument(s).

8 export declare function translateYjsEvent(editor: Editor, event: Y.YEvent): Operation[];
                                                                   ~~~~~~~~


Error: node_modules/slate-yjs/dist/main/applyToSlate/index.d.ts:12:64 - error TS2314: Generic type 'YEvent<T>' requires 1 type argument(s).

12 export declare function applyYjsEvents(editor: Editor, events: Y.YEvent[]): void;
```

It looks like they changed the YEvent definition in version 13.5.28, thus breaking the compilation.
I guess the applyToSlate definitions need to be changed accordingly.

**Comment by BitPhinix** [comment]
`@slate-yjs/core`, `@slate-yjs/react` both properly support both the latest `yjs` and `slate` versions (+ a tone of other enhancements). I'm no longer updating the legacy version of `slate-yjs`, please migrate to `next` to use the latest yjs version
