### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by FindAPattern** [BitPhinix/slate-yjs#338]
Getting a strange error when installing @slate-yjs/react. Looks like the workspace URL in its package.json does not work in NPM. 

```bash
▶ npm -v
8.7.0
▶ node -v
v16.14.2
▶ npm i @slate-yjs/react@latest
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^
```

**Comment by BitPhinix** [comment]
Sorry about this, wasn't aware of https://github.com/changesets/changesets/issues/432. Should be fixed in https://github.com/BitPhinix/slate-yjs/releases/tag/%40slate-yjs%2Freact%400.2.4
