### ISSUE TITLE
Path doesn't match yText, yTarget spans multiple nodes 

### ISSUE THREAD

**Issue by karthikcodes6** [BitPhinix/slate-yjs#354]
I'm getting this error quite often nowadays, any idea what could be the source?

**Comment by BitPhinix** [comment]
Is there any specific scenario/conditions where it occurs for you?

**Comment by karthikcodes6** [comment]
I'm using slate-yjs with platejs I'm getting this error while pasting content from outside into the editor. I'll try to reproduce the issue with a codesandbox. But do you have any clue why this might happen?

**Comment by BitPhinix** [comment]
Did you manage to reproduce this in a codesandbox?

**Comment by BitPhinix** [comment]
Closing this for now, feel free to re-open if it persists or you have more details
