### ISSUE TITLE
The operating error

### ISSUE THREAD

**Issue by umlink** [BitPhinix/slate-yjs#371]
**[ERROR]** A is editing, B deletes all contents, A rolls back, and DB hangs
![image](https://user-images.githubusercontent.com/18066052/196076404-1b2b0b7b-88af-41e4-b250-2be55fdbb366.png)

**Comment by BitPhinix** [comment]
Thanks for reporting; I will take a look soon. Probably can be fixed with a normalization rule to ensure the editor always has content.

**Comment by BitPhinix** [comment]
Addressed in https://github.com/BitPhinix/slate-yjs/pull/377
