### ISSUE TITLE
hocuspocus is no longer open source

### ISSUE THREAD

**Issue by juliankrispel** [BitPhinix/slate-yjs#378]
The backend and frontend example for slate-yjs seems to use the hocuspocus library which is no longer open source. I think it'd be great if there was an open source example that people could use.

I'd be happy to help - some starting points would be greatly appreciated @BitPhinix wdyt

**Comment by BitPhinix** [comment]
As far as I know, hocuspocus will be OSS once it reaches it's 1.0 release. It's sponsorware at the moment, but the 1.0 release is relatively close (the next stable release): https://tiptap.dev/blog/news-on-tiptap-and-hocuspocus

**Comment by BitPhinix** [comment]
It's oss now
