### ISSUE TITLE
Simplify server side setup

### ISSUE THREAD

**Issue by wong2** [BitPhinix/slate-yjs#92]
Hi, thanks for the excellent library!
Usage of this library on client side is pretty simple, but the server side setup is pretty scary: https://github.com/BitPhinix/slate-yjs-example/blob/master/server/server.ts 
It seems this is a modification of version of y-websocket code? Hope we can just import or extend y-websocket instead of modify it's source code

**Comment by BitPhinix** [comment]
Hi @wong2,

Sorry for taking so long. With version 1.0.0 no custom server code is necessary anymore. I updated [slate-yjs-example](https://github.com/BitPhinix/slate-yjs-example) to not include custom server code anymore: https://github.com/BitPhinix/slate-yjs-example/blob/master/src/Client.tsx.

Hope this solves your issue 🤗

**Comment by wong2** [comment]
Awesome!
